export default {
	load 	: "HTMLEvents",
	unload 	: "HTMLEvents",
	abort 	: "HTMLEvents",
	error 	: "HTMLEvents",
	select 	: "HTMLEvents",
	change 	: "HTMLEvents",
	submit 	: "HTMLEvents",
	reset 	: "HTMLEvents",
	focus 	: "HTMLEvents",
	blur 	: "HTMLEvents",
	resize 	: "HTMLEvents",
	scroll 	: "HTMLEvents",

	keypress: "KeyboartEvent",
	keyup 	: "KeyboartEvent",
	keydown : "KeyboartEvent",

	contextmenu : "MouseEvents",
	click 		: "MouseEvents",
	dbclick 	: "MouseEvents",
	mouseout 	: "MouseEvents",
	mouseover 	: "MouseEvents",
	mouseenter 	: "MouseEvents",
	mouseleave 	: "MouseEvents",
	mousemove 	: "MouseEvents",
	mousedown 	: "MouseEvents",
	mouseup 	:"MouseEvents",
	mousewheel 	:"MouseEvents"
};